pub mod eight;
pub mod eighteen;
pub mod eleven;
pub mod fifteen;
pub mod five;
pub mod forty;
pub mod four;
pub mod fourteen;
pub mod nine;
pub mod nineteen;
pub mod seven;
pub mod seventeen;
pub mod six;
pub mod sixteen;
pub mod ten;
pub mod thirteen;
pub mod thirty;
pub mod thirty_eight;
pub mod thirty_five;
pub mod thirty_four;
pub mod thirty_nine;
pub mod thirty_one;
pub mod thirty_seven;
pub mod thirty_six;
pub mod thirty_three;
pub mod thirty_two;
pub mod twelve;
pub mod twenty;
pub mod twenty_eight;
pub mod twenty_five;
pub mod twenty_four;
pub mod twenty_nine;
pub mod twenty_one;
pub mod twenty_seven;
pub mod twenty_six;
pub mod twenty_three;
pub mod twenty_two;
pub mod two;

pub fn run(n: u32) {
    match n {
        1 => six::one(),
        2 => two::run(),
        3 => six::three(),
        4 => four::four(),
        5 => five::five(),
        6 => six::six(),
        7 => seven::seven(),
        8 => eight::eight(),
        9 => nine::nine(),
        10 => ten::ten(),
        11 => eleven::run(),
        12 => twelve::run(),
        13 => thirteen::run(),
        14 => fourteen::run(),
        15 => fifteen::run(),
        16 => sixteen::run(),
        17 => seventeen::run(),
        18 => eighteen::run(),
        19 => nineteen::run(),
        20 => twenty::run(),
        21 => twenty_one::run(),
        22 => twenty_two::run(),
        23 => twenty_three::run(),
        24 => twenty_four::run(),
        25 => twenty_five::run(),
        26 => twenty_six::run(),
        27 => twenty_seven::run(),
        28 => twenty_eight::run(),
        29 => twenty_nine::run(),
        30 => thirty::run(),
        31 => thirty_one::run(),
        32 => thirty_two::run(),
        33 => thirty_three::run(),
        34 => thirty_four::run(),
        35 => thirty_five::run(),
        36 => thirty_six::run(),
        37 => thirty_seven::run(),
        38 => thirty_eight::run(),
        39 => thirty_nine::run(),
        40 => forty::run(),
        _ => unreachable!(),
    }
}
